{
  lib,
  stdenv,
  fetchgit,
  autoreconfHook,
  autoconf-archive,
  pkg-config,
  openssl,
  tpm2-tss,
  writeText,
}:

let
  # The libraries link libcommon statically and export its ~60 `tpm2_*`
  # helpers, which collide with same-named functions in anything that loads
  # them: systemd-sbsign and systemd-measure abort in their own tpm2_create()
  # when given `--private-key-source=provider:tpm2`. Export only the entry
  # points OpenSSL looks up.
  providerSymbols = writeText "provider.map" ''
    { global: OSSL_provider_init; local: *; };
  '';
  engineSymbols = writeText "engine.map" ''
    { global: v_check; bind_engine; local: *; };
  '';
in

stdenv.mkDerivation (finalAttrs: {
  pname = "openssl-tpm2-engine";
  version = "4.4.3";

  src = fetchgit {
    url = "https://git.kernel.org/pub/scm/linux/kernel/git/jejb/openssl_tpm2_engine.git";
    tag = "v${finalAttrs.version}";
    hash = "sha256-Iohgy9bvLjfm4WhgHfk/a7I7YHoV61U+b59i2bnFo2M=";
  };

  patches = [
    # Load the signed-policy signing key via OSSL_STORE instead of only as a
    # PEM file, so policies can be approved with a key on a hardware token.
    ./policy-key-ossl-store.patch
  ];

  postPatch = ''
    # The man pages are generated by running each tool's --help through
    # help2man, which rejects their non-zero exit status.
    substituteInPlace src/tools/Makefile.am \
      --replace-fail 'man1_MANS =' 'disabled_man1_MANS =' \
      --replace-fail 'man7_MANS =' 'disabled_man7_MANS ='

    substituteInPlace src/provider/Makefile.am \
      --replace-fail 'libtpm2_la_LDFLAGS= -no-undefined -avoid-version' \
                     'libtpm2_la_LDFLAGS= -no-undefined -avoid-version -Wl,--version-script=${providerSymbols}'
    substituteInPlace src/engine/Makefile.am \
      --replace-fail 'libtpm2_la_LDFLAGS= -no-undefined -avoid-version' \
                     'libtpm2_la_LDFLAGS= -no-undefined -avoid-version -Wl,--version-script=${engineSymbols}'
  '';

  nativeBuildInputs = [
    autoreconfHook
    autoconf-archive
    pkg-config
  ];

  buildInputs = [
    openssl
    tpm2-tss
  ];

  # Install into our own prefix instead of OpenSSL's store path. Point
  # OPENSSL_MODULES / OPENSSL_ENGINES here to load them.
  configureFlags = [
    "--with-enginesdir=${placeholder "out"}/lib/engines-3"
  ];
  preConfigure = ''
    substituteInPlace configure \
      --replace-fail 'modulesdir=`$PKG_CONFIG --variable=modulesdir libcrypto`' \
                     "modulesdir=$out/lib/ossl-modules"
  '';

  # The test suite needs a TPM simulator and network access.
  doCheck = false;

  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    for lib in $out/lib/ossl-modules/libtpm2.so $out/lib/engines-3/libtpm2.so; do
      leaked=$($NM -D --defined-only "$lib" | awk '$2 == "T" && $3 ~ /^tpm2_/')
      if [ -n "$leaked" ]; then
        echo "$lib still exports tpm2_* symbols:" >&2
        echo "$leaked" >&2
        exit 1
      fi
    done
    $NM -D --defined-only $out/lib/ossl-modules/libtpm2.so | grep -q ' T OSSL_provider_init$'
    $NM -D --defined-only $out/lib/engines-3/libtpm2.so | grep -q ' T bind_engine$'
    runHook postInstallCheck
  '';

  meta = {
    description = "OpenSSL engine and provider for TPM 2.0 keys with policy support";
    homepage = "https://git.kernel.org/pub/scm/linux/kernel/git/jejb/openssl_tpm2_engine.git";
    license = lib.licenses.lgpl21Plus;
    platforms = lib.platforms.linux;
    longDescription = ''
      Unlike tpm2-openssl, it executes the policy stored in the key file (PCR,
      signed PolicyAuthorize, locality, ...) at signing time, so a key can be
      bound to the boot state it may sign in.
    '';
    maintainers = with lib.maintainers; [ andre4ik3 ];
    mainProgram = "create_tpm2_key";
  };
})
